### PR TITLE
Minor cosmetic fix in an example comments

### PR DESCRIPTION
**Pull request by nq-ebaratte**
The diagram was quite unreadable. I just improved the spacing.

### CODE REVIEW

**Comment by mavam** [comment]
The patch itself looks reasonable to me, thanks, but the pull request contains an extra unnecessary merge commit. Please squash the fix into a single commit.

**Comment by Neverlord** [comment]
This got messed up when we changed the coding style a while ago.

Thank you for submitting the patch, but I fixed this ASCII diagram already while porting the examples to the new atom constants (https://github.com/actor-framework/actor-framework/commit/a6cb56a061277f689d833c8a772abe2c618ba17c). :)

**Comment by nq-ebaratte** [comment]
I missed that; no need to bother, then.

**Comment by Neverlord** [comment]
It's not merged to the `master` branch yet, so it's no surprise to me that you've missed it. Will be merged back soon, though.

**Pull request closed without merging**
