### PR TITLE
Requests multiplexing in event-based actors

### PR DESCRIPTION
**Pull request by ufownl**
Relates #378

### CODE REVIEW

**Comment by Neverlord** [comment]
Uh, that's a nice christmas gift. Even though it didn't arrive in time. ;)

Thanks a lot! I'll review this next week.

**Comment by ufownl** [comment]
I have tweaked the code. But what happen with GitHub? The commits of this PR looked so strange.

**Comment by ufownl** [comment]
Oh, I see, I was confused by force pushing.

**Comment by Neverlord** [comment]
Sorry about that. I pushed before realizing that this means you have to rebase your PR too. Could have waited with that.

The PR looks good. I'll check it out and test it tomorrow.

**Comment by Neverlord** [comment]
Merged via https://github.com/actor-framework/actor-framework/commit/d17d2b03433876089febaa8d2c8da2d2d49be629 (I had to resolve a conflict with my local changes, that's why the hash differs).

Thanks for contributing to CAF, you rock!

**Pull request closed without merging**
