### PR TITLE
Fix bug: group brokers do not send group_down_msg

### PR DESCRIPTION
**Pull request by ufownl**
#297

### CODE REVIEW

**Comment by Neverlord** [comment]
ok to test

**Comment by ufownl** [comment]
It seems that gcc4.7 has lambda capture compatibility issues. :-(

**Comment by Hamdor** [comment]
maybe something like this helps: (not tested)
```c++
auto fun = [this](event_based_actor* self) -> behavior {
  self->monitor(m_broker);
  return {
    [=](const down_msg& down) {
      auto msg = make_message(group_down_msg{group(this)});
      send_all_subscribers(self->address(), std::move(msg), self->host());
      self->quit(down.reason);
    }
};
...
m_monitor = spawn(fun);
...
```

**Comment by ufownl** [comment]
I have installed gcc4.7.4 on my machine and compiled `libcaf_core`, but there has no error.

**Comment by Hamdor** [comment]
Yes, GCC 4.7.4 is not affected. But CAF supports down to GCC 4.7.2, thats why one of the Jenkins machines run this old version...

**Comment by ufownl** [comment]
Ok, I see, thanks @Hamdor . I had pushed a new commit to avoid the compilation error.

**Comment by mavam** [comment]
@ufownl Would you mind squashing your commits into a single one?

**Comment by ufownl** [comment]
@mavam Certainly, but how to do it? Commit a new PR?

**Comment by mavam** [comment]
@ufownl The easiest would be to do this: `git rebase -i HEAD~2` and then set the bottom `pick` to `s[quash]`. Thereafter, just force-push to your branch: `git push -f origin HEAD`.

**Comment by ufownl** [comment]
@mavam It has been done. Thanks a lot.

**Comment by mavam** [comment]
:+1:

**Comment by Neverlord** [comment]
Thank you once more @ufownl. You rock. :)

**Pull request merged**
