### PR TITLE
Redesign actor decorators

### PR DESCRIPTION
**Pull request by Lingxi-Li**
1. Give decorators their own identities
2. Fix dot composition behavior to match `f.g(x)=f(g(x))`
3. Make decorators depend on decorated actors, but not vice versa

Relates to #379, #380, #381

### CODE REVIEW

**Comment by Neverlord** [comment]
@Inet-Jenkins test this please

**Comment by Lingxi-Li** [comment]
Honestly, I think the decorators deserve their own test suits. Since some decorator tests are already put in `typed_spawn`, I just tried to fit in there also.

**Comment by Neverlord** [comment]
I agree. Putting the decorator test in a separate suite is a good idea.

**Comment by Lingxi-Li** [comment]
Revised as instructed. Also factored and improved decorator unit tests.

**Comment by Lingxi-Li** [comment]
Revised according to 2nd review. The code is much better now :)

**Comment by Neverlord** [comment]
I merged the PR and applied some streamlining + coding style nitpicks [1] to it: https://github.com/actor-framework/actor-framework/commit/af4f3410c8cd159fce4744917482ce4074660c53

Thanks for contributing to CAF, you rock!

[1] for example:
- `: member(value)` instead of `: member { value }`
- `foo tmp{bar}` instead of `foo tmp { bar };`

**Comment by Neverlord** [comment]
@Lingxi-Li by the way, the new unit tests are pretty good. Please feel free to improve other unit tests in CAF as well. ;)

**Pull request closed without merging**
