### PR TITLE
Refine memory order on `monitorable_actor::exit_reason_`

### PR DESCRIPTION
**Pull request by Lingxi-Li**
May improve performance on certain architectures.

### CODE REVIEW

**Comment by Neverlord** [comment]
"Improve performance" is a bold statement. On x86 it actually makes no difference, because the platform has only atomics + memory barriers and no acquire/release semantics (other comments see review to https://github.com/Lingxi-Li/actor-framework/commit/3b0953a0e2c6ccf54a932c90fc9fffe515c0e726).

Unfortunately this PR hit while I was rewriting the decorator part and adding a new one. So you'd have to rebase.

**Comment by Lingxi-Li** [comment]
I was understanding memory order from a quite high (and thus coarse) level. I was expecting that unless release-acquire constructs are in place, a reader thread may not catch (see) the result of a writer thread, and then period, without any finer analysis. You seem to be working on a much lower level than me with the understanding of underlying mechanisms, and are thus able to give a more refined and relaxed memory order solution. Learned a lot. Gonna update the PR as suggested.

**Comment by mavam** [comment]
> Improves performance.

Have you measured it?

**Comment by Lingxi-Li** [comment]
Revised. Also edited the bold statement.
@mavam As you may have guessed, I haven't done any performance profiling. Should have been careful with my wording.

**Comment by mavam** [comment]
> @mavam As you may have guessed, I haven't done any performance profiling. Should have been careful with my wording.

I'm curious how you started looking into this particular code branch. Did it show in a profiler on a critical path?

**Comment by Lingxi-Li** [comment]
Not really. I'm mostly wandering about, learning the code. From time to time, things come to me that may turn out to be an improvement to the code. So I propose it. Have learned a lot from the code and from the discussions with you guys.

**Comment by Lingxi-Li** [comment]
Revised according to 2nd review.

**Comment by Neverlord** [comment]
Thanks for contributing to CAF, you rock!

**Pull request merged**
