### PR TITLE
Multiple typos fix

### PR DESCRIPTION
**Pull request by andrismednis**

### CODE REVIEW

**Comment by Neverlord** [comment]
Thank you for the fixes! 🎉

Don't worry about the failed style check, I've fixe the formatting after merging.

**Comment by andrismednis** [comment]
Thanks!
I used [codespell](https://github.com/codespell-project/codespell/) to find these typos.
2 more issues you can look at:

1. libcaf_io/caf/io/abstract_broker.hpp, line 176: says
/// Adds the unitialized `scribe` instance `ptr` to this broker.
Probably unitialized  ==> uninitialized ?

2. libcaf_core/caf/intrusive/lifo_inbox.hpp, line 220: relase  ==> release ?
But that is in code, not in comments.

**Comment by Neverlord** [comment]
> I used codespell to find these typos (although with false positives).

I did wonder how you spell-checked the entire code base. Looks like a neat tool! Maybe we should integrate it in our work flow. 😄

@jakobod would you mind fixing the typos in source code?

**Comment by jakobod** [comment]
@Neverlord Not at all. I'll take a look at those in a bit 👍

**Pull request merged**
