### PR TITLE
Separate ASIO backend from 'libcaf_io'

### PR DESCRIPTION
**Pull request by firegurafiku**
If configured with `--with-asio` (`CAF_USE_ASIO`) flag, provide another set of IO libraries:

 * `libcaf_io_asio_shared` alongside with `libcaf_io_shared`
 * `libcaf_io_asio_static` alongside `libcaf_io_static`.

### CODE REVIEW

**Comment by Neverlord** [comment]
@Inet-Jenkins ok to test

**Comment by firegurafiku** [comment]
@Neverlord 

Cannot figure out why Jenkins failed the build? What could mean the following error? 
```
stderr: fatal: reference is not a tree: a64c4d9841885500d94a037c80c702765e811747
```

**Comment by Neverlord** [comment]
@Inet-Jenkins retest this please

**Comment by Neverlord** [comment]
@firegurafiku Jenkins sometimes has its freakouts...

**Comment by Neverlord** [comment]
Just ignore the error on `msbuild`, btw. I currently cannot fix the setup because of a bug in the Jenkins module [1]. Will fix as soon as possible.

[1] https://issues.jenkins-ci.org/browse/JENKINS-28909

**Comment by firegurafiku** [comment]
@Neverlord 

OK, adding a macro would indeed be better.

**Comment by Neverlord** [comment]
Became obsolete in the meantime (see Gitter discussion).

**Pull request closed without merging**
