### PR TITLE
Deprecate `spawn_typed`

### PR DESCRIPTION
**Pull request by ufownl**
Relates #329.

### CODE REVIEW

**Comment by Neverlord** [comment]
@Inet-Jenkins ok to test

**Comment by ufownl** [comment]
Jenkins seems strike again.

**Comment by Hamdor** [comment]
Jenkins is a bit shy today. But everything build successfully :P http://mobi39.cpt.haw-hamburg.de/job/CAF%20Contributions/job/pull%20requests/172/

**Comment by ufownl** [comment]
@Hamdor Glad to hear about this. :)

**Comment by Neverlord** [comment]
@ufownl Thank you once more for your effort. :)

I was quite busy in my topic branch, expect a full review tomorrow. One thing I can already say is: you removed all versions of `spawn_typed` instead of deprecating them via `CAF_DEPRECATED`. Giving users a grace period is much nicer then breaking existing code right away.

**Comment by ufownl** [comment]
`spawn_typed` interfaces have been resumed and been marked with `CAF_DEPRECATED`.

**Comment by Neverlord** [comment]
@Inet-Jenkins retest this please

**Comment by Neverlord** [comment]
The improved meta programming utilities I've mentioned in #329 can be found in [my current topic branch](https://github.com/actor-framework/actor-framework/blob/topic/remoting-overhaul/libcaf_core/caf/infer_handle.hpp). The old interface of `infer_actor_base` and `infer_actor_handle` was too clumsy and a pain to use. Just compare:

```cpp
template <spawn_options Os, typename BeforeLaunch, typename F, class... Ts>
typename std::conditional<
  has_blocking_api_flag(Os),
  actor,
  typename infer_actor_handle<
    typename detail::get_callable_trait<F>::result_type,
    typename detail::tl_head<
      typename detail::get_callable_trait<F>::arg_types
    >::type
  >::type
>::type
spawn_functor(execution_unit* eu, BeforeLaunch cb, F fun, Ts&&... xs) {
```

to

```cpp
template <spawn_options Os, typename BeforeLaunch, class F, class... Ts>
typename infer_handle_from_fun<F>::type
spawn_functor(execution_unit* eu, BeforeLaunch cb, F fun, Ts&&... xs) {
```

While I'm impressed that you pulled that off with the "old and complicated stuff", I *really* would prefer to get rid of all these overly lengthy constructs. You can see the "new magic" in use [here](https://github.com/actor-framework/actor-framework/blob/topic/remoting-overhaul/libcaf_core/caf/experimental/announce_actor_type.hpp).

The branch isn't done yet. But you could rebase your code to 101e27984a46d082b206d804cbbf123ceccf5767 and wait until I merge it back to `develop` to accept the patch. But this is asking you to redo all the work... So I would fully understand it if you would leave this to someone else.

**Comment by ufownl** [comment]
The new meta programming utilities have been used. They are really great!

**Comment by Neverlord** [comment]
@ufownl wow, that was quick. :)

This is looking good on first sight. The topic branch still requires more testing (and bugfixes), so I'll merge this once the code is ready for `develop`.

**Comment by Neverlord** [comment]
I had to cherry-pick this commit because I rebased the topic branch in the meantime. That's why GitHub shows this PR as unmerged.

Thanks for contributing to CAF, you rock!

**Pull request closed without merging**
