### PR TITLE
spawn_in_group variant that allows for multiple groups

### PR DESCRIPTION
**Pull request by ufownl**
relates #306

### CODE REVIEW

**Comment by Neverlord** [comment]
You are quick. :)

I'm happy to merge once the extra heap allocation is gone.

**Comment by ufownl** [comment]
I agree with you, and prefer remain support for arbitrary containers. I'll do that after work. :)

**Comment by Neverlord** [comment]
No rush. :)

**Comment by josephnoir** [comment]
@Inet-Jenkins test this please

**Comment by Neverlord** [comment]
Looks like GCC doesn't like the new template overload: http://mobi39.cpt.haw-hamburg.de/job/CAF%20Contributions/job/pull%20requests/151/label_exp=Linux%20&&%20gcc4.8/console

**Comment by ufownl** [comment]
Hmm.. Maybe I should rename the functions for multiple groups.

**Comment by ufownl** [comment]
I forgot leaving a comment. Actually, it has been done the day after yesterday.

**Comment by Neverlord** [comment]
@Inet-Jenkins test this please

**Comment by Neverlord** [comment]
Looks good. Thanks for contributing to CAF, you rock!

**Pull request merged**
