### PR TITLE
Typed Brokers

### PR DESCRIPTION
**Pull request by ufownl**
#309

### CODE REVIEW

**Comment by Neverlord** [comment]
@Inet-Jenkins test this please

**Comment by Neverlord** [comment]
Wow, this is a lot of work. Thank you!

I probably won't have the time this week to review this in detail, but I'll get back this next week at the latest.

**Comment by ufownl** [comment]
No rush. :) I'll check the compilation error tomorrow. Maybe I didn't open the `CAF_ASSERT`.

**Comment by ufownl** [comment]
The compilation error has been fixed.

**Comment by Neverlord** [comment]
@Inet-Jenkins ok to test

**Comment by ufownl** [comment]
The compilation errors with GCC have been fixed. It seems that GCC4.8 is necessary to be saved on my computer.

**Comment by ufownl** [comment]
Actually, It isn't compatible problem between GCC and Clang, and I have corrected the wrong implementation.

**Comment by Neverlord** [comment]
Just a heads-up on this PR: I'm currently re-thinking the functor-based actors, as they currently cause too much code for a comparable little feature. I would like to streamline this a bit to reduce overall code size of CAF. I would then update your PR as well.

The PR itself looks good, btw (though I didn't review all changes yet).

**Comment by Neverlord** [comment]
Took a bit longer since it was more work than expected. Your unit test setup didn't work properly (you tested against `broker` on the other side, not `typed_broker`) and I reduced a lot of code redundancy by extending `local_actor` in `abstract_broker`. The `typed_actor` has now type aliases for `broker_pointer` and `broker_base`. You need to define typed interfaces other actors can use, so there's no way around a `typed_actor` definition. With the forward declaration, we can at least get rid of any redundancy here.

Also, I merged the code with latest develop and got rid of all `functor_based` classes. Please note we have updated our coding style for future PRs. :)

Thanks for contributing to CAF, you rock!

**Comment by Neverlord** [comment]
By the way, this was the 100th closed pull request. :tada:

**Pull request merged**
