### PR TITLE
Support array members in `announce`

### PR DESCRIPTION
**Pull request by ufownl**
Relates #350

### CODE REVIEW

**Comment by tbenthompson** [comment]
As I discovered working on this problem, this only fixes the compile-time error. Announcing an array type will still fail at runtime, without making some internal support for serializing arrays of primitives. I get the error:
[ERROR] NONE::uniform_typeid: uniform_typeid(): A4_i has not been announced
exception St13runtime_error: uniform_typeid(): A4_i has not been announced
meaning that int[4] has not been announced.

Let me know if you plan to work on this more, as I did almost the exact same thing as you, went to write a unit test, noticed it failed and am currently trying to figure out what to do next.

**Comment by ufownl** [comment]
Hm, it's my negligence. I'll look into it.

**Comment by tbenthompson** [comment]
Don't. I just got an implementation working. I'll set up a pull request in a moment.

**Comment by tbenthompson** [comment]
See #352.

**Comment by Neverlord** [comment]
@ufownl Just a quick heads-up: I reviewed this already and I got nothing to complain about. We recently changed our Jenkins setup (to include our submodules) and I'm still fighting some problems there. I'll merge this as soon as possible.

**Comment by ufownl** [comment]
Hope you solve them smoothly. :)

**Comment by Neverlord** [comment]
@Inet-Jenkins test this please

**Comment by Neverlord** [comment]
Not exactly smoothly, but it seems we can finally move on. :)

Thanks for contributing to CAF, you rock!

**Comment by ufownl** [comment]
> but it seems we can finally move on. :)
Good to know.

**Pull request merged**
