### PR TITLE
Forwarding to and from typed actors

### PR DESCRIPTION
**Pull request by ufownl**
Relates #319.

### CODE REVIEW

**Comment by Neverlord** [comment]
I think this PR is a start, but it would make sense to grant dynamically-typed actors access to the new `delegate` functionality as well.

**Comment by ufownl** [comment]
I have moved `delegate` into `local_actor` and added a test for it. Now the dynamically-typed actors can access to the new `delegate` functionality.

**Comment by Neverlord** [comment]
@Inet-Jenkins ok to test

**Comment by Neverlord** [comment]
It still misses an overload for `delegate(const actor& dest, ...)`, though.

**Comment by ufownl** [comment]
The new solution you offered has been implemented, and the overload for `delegate(const actor& dest, ...)` also has been added.

**Comment by Neverlord** [comment]
Amazing work, as always. I cleaned up the code a bit and renamed the `detail::delegate_helper` to `delegated`. This is because users need to be able to type this name. Also, delegating to a dynamically typed actor returns `void` (there's really nothing that could be inferred here).

Thanks for contributing to CAF, you rock!

**Pull request merged**
