### PR TITLE
Add biicode build support

### PR DESCRIPTION
**Pull request by outro56**
I updated the biicode support and pushing into the develop branch

### CODE REVIEW

**Comment by Neverlord** [comment]
ok to test

**Comment by Neverlord** [comment]
Thanks again. Should go live mid next week if I have the scripts for auto-publishing to Bii done.

**Comment by Neverlord** [comment]
@outro56 there you go: https://www.biicode.com/caf_bot/actor-framework

**Comment by Neverlord** [comment]
@outro56 could you give me a short step-by-step guide how to use CAF from Bii for the readme file?

**Comment by outro56** [comment]
Sure, will send that to you this evening when I get home. 
--
Chike 
On May 18, 2015 9:33 AM, Dominik Charousset <notifications@github.com> wrote:@outro56 could you give me a short step-by-step guide how to use CAF from Bii for the readme file?

**Comment by outro56** [comment]
The short of it is that users would need include the caf header files like so
#include "caf_bot/actor-framework/libcaf_core/caf/all.hpp"
And then run "bii find" before call "bii build" on the command line. This would find and download all the dependencies need for building libcaf. 
I haven't tried this yet, don't have access to my laptop. Will do so later and also provide instructions on how to keep the includes short and referencing the other libraries in libcaf. 
--
Chike 
On May 18, 2015 9:33 AM, Dominik Charousset <notifications@github.com> wrote:@outro56 could you give me a short step-by-step guide how to use CAF from Bii for the readme file?

**Comment by Neverlord** [comment]
No rush. :)

If it's too long to fit into a few markdown lines, we could make a Wiki entry for Bii and add a link to readme instead (you can edit the Wiki directly, btw.).

**Comment by outro56** [comment]
## Using actor-framework in your biicode projects

The official actor-framework project channel is published under [caf_bot/actor-framework](https://www.biicode.com/caf_bot/actor-framework). The following sub projects are currently published in the block
* libcaf_core
* libcaf_io
* libcaf_riac
* libcaf_opencl (*depends on OpenCL which is not distributed as part of actor-framework*)

**NOTE:** You do not need to download or have the actor-framework installed on your machine. Biicode will automatically do that for you during the build process. For more information visit this [link](http://docs.biicode.com/c++/gettingstarted.html) on the biicode website.

To use actor-framework in your project reference the header file as follows 

``#include "caf_bot/actor-framework/libcaf_core/caf/all.hpp"``

Then run ``bii find`` so that biicode can resolve and download the files.

**Comment by outro56** [comment]
@Neverlord let me know if thats enough or too much for the read me

**Comment by mavam** [comment]
Also, this year at C++Now there was a talk about biicode. Slides available here: https://github.com/boostcon/cppnow_presentations_2015/raw/master/files/dep_manager_workshop.pdf

**Comment by outro56** [comment]
The one thing I love about biicode is that I don't have to be an expert in CMake :)

ps: you might also want to publish a stable channel for the library (http://docs.biicode.com/c++/publishing.html#tag-a-version) currently its only on the dev channel

**Comment by Neverlord** [comment]
Thank you very much for the guide. :)

I streamlined it a bit and added a new section to the readme. @mavam I also added Homebrew. Could you complement the readme with a FreeBSD section?

**Comment by Neverlord** [comment]
> ps: you might also want to publish a stable channel for the library (http://docs.biicode.com/c++/publishing.html#tag-a-version) currently its only on the dev channel

Yes, 0.14 is going to be the first stable tag on Bii.

**Comment by mavam** [comment]
@Neverlord I can add FreeBSD instructions. Sorry if I missed it, but *where* should I add it? To the README?

**Comment by Neverlord** [comment]
Yes, to the readme near the Homebrew section. :)

**Pull request merged**
