### PR TITLE
Add the periodic heartbeat mechanism of BASP

### PR DESCRIPTION
**Pull request by ufownl**
Relates #431.

### CODE REVIEW

**Comment by Neverlord** [comment]
I discussed this with @josephnoir a bit and we both wonder why you do this ping/pong. A heartbeat message usually is one-way only. Doing this request/response-style heartbeat doubles the amount of periodic messages. If you have 10 nodes, a usual heartbeat mechanism would send 90 heartbeat messages per cycle (each node sends its heartbeat to the other nine). You send 180 messages instead.

The purpose of heartbeats is to signalize to *others* that we are still alive. By receiving their heartbeats in turn, we can determine whether or not they are still alive. Since CAF is currently only using TCP, there is not even a need to count how many heartbeats we received per second. In a TCP setting, heartbeats are only there to trigger periodic communication in order to propagate node failures quicker if no actual actor communication is happening.

For BASP, this would mean to add one new message type (`heartbeat`) that is recognized by receivers but doesn't trigger any other code. Or maybe add a new `instance::callee::handle_heartbeat(const node_id& nid)` event handler is currently empty in `basp_broker_state`. This would allow us to add some custom code later that perhaps tries to detect weird behaviors of nodes (heavy jitter between received heartbeats could indicate an overloaded network for example).

**Comment by ufownl** [comment]
> I discussed this with @josephnoir a bit and we both wonder why you do this ping/pong. 

Hmm... I think I trapped in a thinking pattern. In the project of our company, the client periodically send a heartbeat-ping to the server and the server response a heartbeat-pong. Then both of them can determine   whether or not peer endpoint is alive and measure the delay between them.

> In a TCP setting, heartbeats are only there to trigger periodic communication in order to propagate node failures quicker if no actual actor communication is happening.

So, the pattern above does not suit CAF. I'll do the revision soon.

**Comment by ufownl** [comment]
Revision done.

**Comment by ufownl** [comment]
> Seems correct, but the commit only says "Add the periodic heartbeat mechanism of BASP". Streamlining code is fine, but it needs to be documented and properly motivated to be transparent to other developers. :)
> 
> It also makes reviewing PRs tedious if changes are seemingly unrelated to the commit description.

You are right, I'll pay attention afterward. :)

**Comment by ufownl** [comment]
2nd revision done.

**Comment by Neverlord** [comment]
I have one complain regarding the commit itself. It breaks in the summary line. Here's the relevant part from our contribution guide:

Commit Message Style
--------------------

- The first line succintly summarizes the changes in no more than 50
  characters. It is capitalized and written in and imperative present tense:
  e.g., "Fix bug" as opposed to "Fixes bug" or "Fixed bug".

- The first line does not contain a dot at the end. (Think of it as the header
  of the following description).

- The second line is empty.

- Optional long descriptions as full sentences begin on the third line,
  indented at 72 characters per line.


A short commit message in this case could be: "Add heartbeats to BASP; streamline basp_broker". That you streamlined handling of `connection_closed_msg` would then belong into the long description.

Two minor issues with the patch itself:

- "heartbeat period" sounds odd, the common term is "heartbeat interval"
- heartbeats currently have second resolution, which is rather long and quite coarse; usually, systems have something like 250ms intervals, so the parameter should use milliseconds instead

**Comment by ufownl** [comment]
Tweaks done.

**Comment by Neverlord** [comment]
@Inet-Jenkins test this please

**Comment by Neverlord** [comment]
Thank you once more for contributing to CAF, you rock! :)

**Pull request merged**
