### PR TITLE
Fix bug.

### PR DESCRIPTION
**Pull request by ufownl**
After the calling of local_actor::quit, if m_pending_responses is not
empty or on_exit did set a new behavior, no matter what the exit reason
was, it will be changed to exit_reason::normal at last. So I think we
should record the exit reason at right time and resume it after the
behaviors and responses are all handled.

### CODE REVIEW

**Comment by Neverlord** [comment]
Setting a new behavior in `on_exit()` "revives" the actor. Dropping the previous exit reason is the intended behavior in this case, since you explicitly abort shutting the actor down.

Could you track down the bug related to `m_pending_responses`? The actor should simply ignore pending responses during shutdown. Where is it revived if the set isn't empty?

**Comment by ufownl** [comment]
It is revived incorrect at the test case:
client
```C++
#include <caf/all.hpp>
#include <caf/io/all.hpp>
#include <iostream>
#include "util.hpp"

void hello_world(caf::event_based_actor* self, const caf::actor& buddy)
{
	caf::aout(self) << "hello_world_actor[" << self->address() << "]" << std::endl;

	for (int i = 0; i < 5; ++i)
	{
		self->sync_send(buddy, "Hello, world!").then([self] (const std::string& what)
				{
					caf::aout(self) << "thread[" << std::this_thread::get_id() << "] actor[" << self->address() << "]: " << what << std::endl;
				});
	}
}

caf::behavior hello_client(caf::event_based_actor* self, const std::string& host, uint16_t port)
{
	using hello_atom = caf::atom_constant<caf::atom("hello")>;

	caf::aout(self) << "hello_client_actor[" << self->address() << "]" << std::endl;

	self->trap_exit(true);
	self->send(self, hello_atom::value);

	return {
		[self, host, port] (hello_atom)
		{
			caf::aout(self) << "Connecting and sending \"Hello, world!\"." << std::endl;

			try
			{
				auto mirror_actor = caf::io::remote_actor(host, port);
				self->monitor(mirror_actor);

				self->spawn<caf::linked>(hello_world, mirror_actor);
			}
			catch (const caf::network_error& e)
			{
				caf::aout(self) << e.what() << std::endl;
				self->send(self, hello_atom::value);
			}
		},
		[self] (const caf::down_msg& msg)
		{
			caf::aout(self) << "actor[" << msg.source << "] down_msg: " << caf::exit_reason::as_string(msg.reason) << std::endl;

			if (msg.reason == caf::exit_reason::remote_link_unreachable)
				self->send(self, hello_atom::value);
		},
		[self] (const caf::exit_msg& msg)
		{
			caf::aout(self) << "actor[" << msg.source << "] exit_msg: " << caf::exit_reason::as_string(msg.reason) << std::endl;

			if (msg.reason != caf::exit_reason::unhandled_sync_failure)
				self->quit(msg.reason);
		},
		caf::others >> [self]
		{
			caf::aout(self) << "unexcepted: " << self->current_message() << std::endl;
		}
	};
}

caf::optional<uint16_t> as_uint16(const std::string& str)
{
	return static_cast<uint16_t>(stoul(str));
}

int main(int argc, char* argv[])
{
	caf::message_builder(argv + 1, argv + argc).apply({
				on(caf::val<std::string>, as_uint16) >> [] (const std::string& host, uint16_t port)
				{
					caf::spawn(hello_client, host, port);
				},
				caf::others >> []
				{
					std::cerr << "Usage: distr_hello <host> <port>" << std::endl;
				}
			});
	caf::await_all_actors_done();
	caf::shutdown();
	return 0;
}
```
server
```C++
#include <caf/all.hpp>
#include <caf/io/all.hpp>
#include <iostream>
#include <thread>
#include "util.hpp"

caf::behavior mirror_worker(caf::event_based_actor* self)
{
	return {
		[self] (const std::string& what)
		{
			for (int i = 0; i < 5; ++i)
			{
				caf::aout(self) << "thread[" << std::this_thread::get_id() << "] actor[" << self->address() <<  "] tick[" << i << "]: " << what << std::endl;
				std::this_thread::sleep_for(std::chrono::seconds(1));
			}

			self->quit();

			return std::to_string(rand()) + std::string(what.rbegin(), what.rend());
		}
	};
}

caf::behavior mirror(caf::event_based_actor* self)
{
	self->trap_exit(true);

	static int exit_trigger = 4;

	return {
		[self] (const std::string&)
		{
			auto worker = self->spawn<caf::linked>(mirror_worker);
			self->forward_to(worker);
		},
		[self] (const caf::exit_msg& msg)
		{
			caf::aout(self) << "thread[" << std::this_thread::get_id() << "] actor[" << self->address() <<  "]: worker_actor[" << msg.source << "] exit" << std::endl;
			if (exit_trigger-- == 0) exit(-1);
		},
		caf::others >> []
		{
			return "This is default handler.";
		}
	};
}

caf::optional<uint16_t> as_uint16(const std::string& str)
{
	return static_cast<uint16_t>(stoul(str));
}

int main(int argc, char* argv[])
{
	caf::message_builder(argv + 1, argv + argc).apply({
				on(as_uint16) >> [] (uint16_t port)
				{
					auto mirror_actor = caf::spawn(mirror);
					port = caf::io::publish(mirror_actor, port, nullptr, true);
					std::cout << "mirror_actor has published on port[" << port << "]." << std::endl;
				},
				caf::others >> []
				{
					std::cerr << "Usage: distr_mirror <port>" << std::endl;
				}
			});
	caf::await_all_actors_done();
	caf::shutdown();
	return 0;
}
```
output of client on my macbook
```
hello_client_actor[2@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3110]
Connecting and sending "Hello, world!".
hello_world_actor[8@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3110]
thread[0x10a47e000] actor[8@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3110]: 282475249!dlrow ,olleH
actor[2@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3104] down_msg: remote_link_unreachable
Connecting and sending "Hello, world!".
thread[0x10a3fb000] actor[8@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3110]: 984943658!dlrow ,olleH
thread[0x10a3fb000] actor[8@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3110]: 1622650073!dlrow ,olleH
thread[0x10a3fb000] actor[8@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3110]: 16807!dlrow ,olleH
[ERROR] NONE::new_tcp_connection_impl: could not connect to to localhost on port 10000
network_error: could not connect to localhost
actor[8@475bab8c60bf9bdc0b90d0da0b824df4ade13460:3110] exit_msg: normal
```
log of client about actor8, sync failure occurred in actor8 clearly
```
1430878093 DEBUG actor8 0x10a584000 caf.event_based_actor.functor_based resume local_actor.cpp:614 initialize actor
1430878093 DEBUG actor8 0x10a584000 caf.event_based_actor.functor_based initialize event_based_actor.cpp:41 make_behavior() did not return a behavior, has_behavior() = 1
1430878093 DEBUG actor8 0x10a584000 caf.event_based_actor.functor_based resume local_actor.cpp:665 no more element in mailbox; going to block
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "282475249!dlrow ,olleH" ), ptr->mid = 9223372036854775813, awaited_id = 9223372036854775813
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based invoke_from_cache local_actor.cpp:780 0 elements in cache
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "16807!dlrow ,olleH" ), ptr->mid = 9223372036854775809, awaited_id = 9223372036854775812
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based resume local_actor.cpp:665 no more element in mailbox; going to block
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "1622650073!dlrow ,olleH" ), ptr->mid = 9223372036854775810, awaited_id = 9223372036854775812
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based resume local_actor.cpp:665 no more element in mailbox; going to block
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "984943658!dlrow ,olleH" ), ptr->mid = 9223372036854775811, awaited_id = 9223372036854775812
1430878098 DEBUG actor8 0x10a47e000 caf.event_based_actor.functor_based resume local_actor.cpp:665 no more element in mailbox; going to block
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@sync_exited ( 8, 475bab8c60bf9bdc0b90d0da0b824df4ade13460, 3110, 257 ), ptr->mid = 9223372036854775812, awaited_id = 9223372036854775812
1430878103 WARN  actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:363 sync failure occured in actor with ID 8
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based operator() local_actor.cpp:587 on_exit did set a new behavior
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_from_cache local_actor.cpp:780 3 elements in cache
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "16807!dlrow ,olleH" ), ptr->mid = 9223372036854775809, awaited_id = 9223372036854775811
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "1622650073!dlrow ,olleH" ), ptr->mid = 9223372036854775810, awaited_id = 9223372036854775811
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "984943658!dlrow ,olleH" ), ptr->mid = 9223372036854775811, awaited_id = 9223372036854775811
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_from_cache local_actor.cpp:780 2 elements in cache
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "16807!dlrow ,olleH" ), ptr->mid = 9223372036854775809, awaited_id = 9223372036854775810
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "1622650073!dlrow ,olleH" ), ptr->mid = 9223372036854775810, awaited_id = 9223372036854775810
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_from_cache local_actor.cpp:780 1 elements in cache
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based invoke_message local_actor.cpp:347 handle as synchronous response: ptr->msg = @<>+@str ( "16807!dlrow ,olleH" ), ptr->mid = 9223372036854775809, awaited_id = 9223372036854775809
1430878103 INFO  actor8 0x10a3fb000 caf.event_based_actor.functor_based cleanup abstract_actor.cpp:230 cleanup actor with ID 8; exit reason = 1
1430878103 INFO  actor8 0x10a3fb000 caf.detail.actor_registry erase actor_registry.cpp:83 erased actor with ID 8, reason 1
1430878103 DEBUG actor8 0x10a3fb000 caf.detail.actor_registry dec_running actor_registry.cpp:111 new_val = 2
1430878103 DEBUG actor8 0x10a3fb000 caf.event_based_actor.functor_based resume local_actor.cpp:651 actor exited
```
I tracked down it related to `m_pending_responses` at beginning, so my first solution is calling `m_pending_responses.clear()` after `bhvr_stack().cleanup()`. But I found it may ignore the responses witch has been completed as the output above, so I commit my second solution here.
If setting a new behavior in `on_exit()` should revives the actor as you said, the behavior stack and pending responses should be handled separately in `done_cb` I think.

**Comment by Neverlord** [comment]
Thanks for the detailed test case. I would like to find a solution that doesn't require a new member variable for all actors, though. I hope I can track down the issue with the code and log output you provided and find a way avoiding the extra field.

**Comment by ufownl** [comment]
I found that if the actor has responses, the third parameter of `local_actor::invoke_message` is only used for matching responses, otherwise the parameter seems be useless. And the current implementation of response matching is nearly iterating `std::forward_list` per message and has no guarantee of response processing order (source of this issue). I think we can use associative container instead of `std::forward_list` for declaring `m_pending_responses`. So that we can use the message id for matching response directly. This solution can reduce time complexity of response matching and has guarantee of response processing order.

**Pull request closed without merging**
