### PR TITLE
Optimize serialization by using type numbers

### PR DESCRIPTION
**Pull request by outro56**

### CODE REVIEW

**Comment by Neverlord** [comment]
Test this please, Jenkins.

**Comment by Neverlord** [comment]
test this please

**Comment by Neverlord** [comment]
Um.. are you sure this is the full patch? It only contains changes to `libcaf_core/test/serialization.cpp`.

**Comment by outro56** [comment]
hmm yeah you are right. I will fix that. 
mistake on my part. originally branched off master and re-read the contribute.md file and figured had to PR to develop branch. I guess didn't cherry-pick correctly

**Comment by outro56** [comment]
Just updated the PR with the missing commits.

**Comment by Neverlord** [comment]
ok to test

**Comment by Neverlord** [comment]
@outro56 Does not compile on GCC 4.7 and 4.8: http://mobi39.cpt.haw-hamburg.de/job/CAF%20Contributions/job/pull%20requests/133/

Some bug with variadic functions and lambdas: http://mobi39.cpt.haw-hamburg.de/job/CAF%20Contributions/job/pull%20requests/133/label_exp=Linux%20&&%20gcc4.8/console

Maybe you can move the `tie` out of the lambda?

**Comment by outro56** [comment]
Haha silly Gcc, probably has issue with generic lambda capture for  variations types. 
I'll look into it. 
--
Chike
Sent from my phone 
On May 9, 2015 3:48 PM, Dominik Charousset <notifications@github.com> wrote:@outro56 Does not compile on GCC 4.7 and 4.8: http://mobi39.cpt.haw-hamburg.de/job/CAF%20Contributions/job/pull%20requests/133/

Some bug with variadic functions and lambdas: http://mobi39.cpt.haw-hamburg.de/job/CAF%20Contributions/job/pull%20requests/133/label_exp=Linux%20&&%20gcc4.8/console

Maybe you can move the tie out of the lambda?

**Comment by outro56** [comment]
Lifted the first "tie" expression out of the lambda

**Comment by Neverlord** [comment]
Jenkins seems to be happy. Great. Thank you very much for the patch. One last request: could you please squash the commits?

**Comment by outro56** [comment]
I squashed the commits but then ended up deleting my remote branch and push again. Not sure if thats what you wanted me to do, or just PR from another branch.

**Comment by Neverlord** [comment]
It would have been enough to squash in your local branch and override the remove branch using `git push -f origin...`. The Pull Request gets updated automatically if you force-push a branch. Saves you some work as well. :)

**Comment by outro56** [comment]
Good to know…for next time :)

**Pull request closed without merging**
