### PR TITLE
Add new unit testing framework.

### PR DESCRIPTION
**Pull request by mavam**
This patch contains the new unit testing framework per #160.

### CODE REVIEW

**Comment by Neverlord** [comment]
test this please

**Comment by Neverlord** [comment]
test this please

**Comment by Neverlord** [comment]
test this please

**Comment by Neverlord** [comment]
test this please

**Comment by Neverlord** [comment]
test this please

**Comment by Neverlord** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Neverlord** [comment]
@Hamdor is this PR complete now?

**Comment by Hamdor** [comment]
If the opencl part is working, had no setup to verify the opencl test.

**Comment by Hamdor** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Hamdor** [comment]
retest this please

**Comment by Neverlord** [comment]
retest this please

**Comment by Neverlord** [comment]
Jenkins always tests the wrong commit, I'll re-open this PR to get it properly tested.

**Pull request closed without merging**
