### PR TITLE
Achieve complete type safe of `typed_broker`

### PR DESCRIPTION
**Pull request by ufownl**
Relates #309 .

We can just enforcing all message handlers on the typed actors that they are used as server.

### CODE REVIEW

**Comment by ufownl** [comment]
I have tried `std::is_convertible`, it didn't work.

**Comment by Neverlord** [comment]
It does, my example code was a bit incorrect. It used to be `handle::extend<...>::type`, which is a bit verbose for my taste anyway. I changed it to accept `handle::extend<...>` instead [1] and also verified that `std::is_convertible` works as expected in the `typed_spawn` unit tests.

So the preferred syntax should work for you after a rebase.

[1] https://github.com/actor-framework/actor-framework/commit/0dc600510a1d4f85cb884035f6f151e08b55b5aa

**Comment by ufownl** [comment]
```C++
// check invariants of type system
using dummy1 = typed_actor<reacts_to<int, int>,
                           replies_to<double>::with<double>>;

//using dummy2 = dummy1::extend<reacts_to<ok_atom>>;
using dummy2 = typed_actor<reacts_to<ok_atom>>;

static_assert(std::is_convertible<dummy2, dummy1>::value,
              "handle not assignable to narrower definition");
```
It has no compilation error on my computer, does it work as expected?

**Comment by Neverlord** [comment]
> It has no compilation error on my computer, does it work as expected?

Crap. The handles are always assignable and only check via `static_assert` if the assignment is correct. I'm working on a fix.

**Comment by Neverlord** [comment]
I'm really sorry for not double-checking this prior to pushing the code to GitHub. I've added a counter-test to the unit test and use SFINAE to make assigning invalid handles impossible: https://github.com/actor-framework/actor-framework/commit/b6a18114fe374460a17f065f04dc09dbdf2f0037

Thank you for your patience (and double-checking the nonsense I wrote). :)

**Comment by ufownl** [comment]
Now, it works fine! And the newest commit has been pushed. :)

**Comment by Neverlord** [comment]
@Inet-Jenkins ok to test

**Comment by ufownl** [comment]
Jenkins didn' work, what's wrong with it?

**Comment by Neverlord** [comment]
Sometimes Jenkins picks up the wrong hash for some reason.

@Inet-Jenkins retest this please

**Comment by ufownl** [comment]
Seems Jenkins hates this PR.

**Comment by Neverlord** [comment]
Looks like it..

**Pull request merged**
