### PR TITLE
Add stream `<<` support for types with `to_string()`

### PR DESCRIPTION
**Pull request by Lingxi-Li**
Now, you can `os << x` instead of `os << to_string(x)`. What's more, in the future, you implement `to_string()` only, and you will have `os << x` support for free :-)

### CODE REVIEW

**Comment by ufownl** [comment]
In my opinion the overload operators you added are unnecessary. Because in most cases, the objects of these classes should be printed using `actor_ostream` rather than `std::ostream'.

**Comment by Lingxi-Li** [comment]
The unit testing framework uses `std::ostringstream` for output (see [here](https://github.com/actor-framework/actor-framework/blob/topic/actor-system/libcaf_test/caf/test/unit_test.hpp#L187)). Besides, CAF should allow easy use with the standard library. One should use `actor_stream` for direct output, but what if he or she wants to use `std::ostringstream` to compose custom strings?

**Comment by Lingxi-Li** [comment]
Just found a better solution (see [here](http://stackoverflow.com/a/34946808/1348273)). PR updated.

**Comment by Neverlord** [comment]
This PR has too much (repetitive) code for such a little addition. Even the current solution for `to_string` is not ideal. We discussed this with @mavam a while ago. A modified version of his concept-based solution in VAST is the way to go going forward. This could also be easily extended to include `operator<<` etc.

Speaking about going forward, maybe we can safe some time if we discuss this in chat before you work on PRs. ;)

**Comment by Lingxi-Li** [comment]
It's OK. No time wasted really. I've learned a lot through the process :-) In fact, I think this should be something to be done by the standard library, and have opened a [topic](https://groups.google.com/a/isocpp.org/d/topic/std-proposals/q3WCpLp1xmQ/discussion) on the std discussion group.

**Pull request closed without merging**
