### PR TITLE
Add INI parser

### PR DESCRIPTION
**Pull request by 1blankz7**
This topic relates to issue #340 and introduces a INI parser with no external dependencies.

### CODE REVIEW

**Comment by Neverlord** [comment]
So... sorry for the long silence. While there's nothing "wrong" with the INI class, it is quite heavyweight and inflexible. Such an interface makes it hard to add support for something else, like JSON for example, in the future.

You also store *a lot* of strings unnecessarily. The map is good idea when having it persist for the duration of the program, but that's not the case in CAF. Here is a snipped how CAF would want to use the parser:

```cpp
// converts a `variant<string, double, int64_t, bool>` to a `message`
struct to_message_visitor : static_visitor<message> {
  message operator()(string& value) {
    return make_message(std::move(value));
  }
  message operator()(int64_t value) {
    return make_message(value);
  }
  message operator()(bool value) {
    return make_message(value);
  }
};

enum class config_format {
  auto_detect,
  ini,
  json
};

using config_value = variant<string, double, int64_t, bool>;

using config_consumer = std::function<void (string, config_value)>;

void parse_config(const string& file_name, 
                  config_format cf = config_format::auto_detect) {
  if (cf == config_format::auto_detect) {
    if (file_name.size() < 5)
      return;
    if (file_name.compare(file_name.size() - 4, 4, ".ini"))
      parse_config(file_name, config_format::ini);
    // else if ... json ...
    else
      std::cerr << "unknown config file format" << std::endl;
    return;
  }
  struct consumer {
    consumer() {
      config_server_ = whereis(atom("ConfigServ"));
    }

    consumer(const consumer&) = default;
    consumer& operator=(const consumer&) = default;

    void operator()(string key, config_value value) const {
      to_message_visitor v;
      anon_send(config_server_, put_atom::value, std::move(key),
                apply_visitor(value, v));
    }

    actor config_server_;
  };
  switch (cf) {
    case config_format::ini:
      detail::parse_ini(file_name, consumer);
      break;
    case config_format::json:
      detail::parse_json(file_name, consumer);
      break;
    // ...
  }
}
```

This code (properly split) would belong to `libcaf_core/caf/parse_config.hpp` and `libcaf_core/src/parse_config.cpp`. 

Ideally, your parser consists of one function: `parse_ini(config_consumer f)`. This removes a lot of verbose boilerplate code on your end. Since the parser is not meant for users, it would belong to `libcaf_core/caf/detail/parse_ini.hpp`.

You also don't need additions such as the trim functions to the `string_algorithms.hpp` header. It is much cheaper to not add unwanted characters to the string in the first place. Here's a trimmed down version of your current `parse` member function that also doesn't store all lines but handles them immediately:

```cpp
void ini_parser::parse() {
  using std::find_if;
  using std::isspace;
  using iterator = string::iterator;
  auto find_non_ws = [](iterator first, iterator end) -> iterator {
    return find_if_not(first, end, isspace);
  };
  string group;
  string line;
  size_t ln = 0; // line number
  while (getline(raw_data_, line)) {
    ++ln;
    // get begin-of-line (bol) and end-of-line (eol), ignoring whitespaces
    auto eol = find_if_not(line.rbegin(), line.rend(), isspace).base();
    auto first = find_if_not(line.begin(), eol, isspace);
    // ignore empty lines and lines starting with ';' (comment)
    if (bol == eol || *bol == ';')
      continue;
    // do we read a group name?
    if (*bol == '[') {
      if (*(eol - 1) != ']')
        cerr << "error in line " << ln << ": missing ] at end of line" << endl;
      else
        group.assign(bol + 1, eol - 1);
      // skip further processing of this line
      continue;
    }
    // do we have a group name yet? (prohibit ungrouped values)
    if (group.empty()) {
      cerr << "error in line " << ln << ": value outside of a group" << endl;
      continue;
    }
    // position of the equal sign
    auto eqs = find(bol, eol, '=');
    if (eqs == eol) {
      cerr << "error in line " << ln << ": no '=' found" << endl;
      continue;
    }
    if (bol == eqs) {
      cerr << "error in line " << ln << ": line starting with '='" << endl;
      continue;
    }
    if ((eqs + 1) == eol) {
      cerr << "error in line " << ln << ": line ends with '='" << endl;
      continue;
    }
    // our keys have the format "<group>.<config-name>"
    auto key = group;
    key += '.';
    // ignore any whitespace between config-name and equal sign
    key.insert(key.end(), bol, find_if(bol, eqs, isspace));
    // begin-of-value, ignoreing whitespaces after '='
    auto bov = find_if_not(eqs + 1, eol, isspace);
    // auto-detect what we are dealing with
    const char* true_str = "true";
    const char* false_str = "false";
    if (std::equal(bov, eol, true_str)) {
      f(std::move(key), true);
    } else if (std::equal(bov, eol, false_str)) {
      f(std::move(key), false);
    } else if (*bov == '"') {
      // found a string, start escaping string sequence
    } else // ... check whether we have a double or integer value ...
  }
}
```

It is of course OK to store everything into a map for your unit test.

```cpp
namespace {

class fixture {
  void parse(const char* cstr) {
    std::stringstream ss;
    ss << cstr;
    auto f = [&](std::string key, config_value value) {
      values.emplace(std::move(key), std::move(value));
    };
  }
  std::map<std::string, config_value> values;
};

template <class T>
bool value_is(const config_value& cv, const T& what) {
  const T* ptr = get<T>(&cv);
  return ptr != nullptr && *ptr == what;
}

constexpr const char* case1 = R"__(
[scheduler]
policy="work-sharing"
max-threads=2

[middleman]
automatic-connections=true

[nexus]
host="127.0.0.1"
port=4242

[cash]
greeting="Hi there, this is \"CASH\"!\n~~~ use at your own risk ~~~\n"
)__";

} // namespace <anonymous>

CAF_TEST_FIXTURE_SCOPE(parse_ini_tests, fixture)

CAF_TEST(test_case1) {
  parse(case1);
  CAF_CHECK(values.count("nexus.port") > 0);
  CAF_CHECK(value_is(values["nexus.port"], int64_t{4242}));
  // ...
}

```

**Comment by 1blankz7** [comment]
Would it be better if I squash the three commits together?

**Comment by Neverlord** [comment]
Yes. This makes reviewing much easier and also keeps the history clean.

**Comment by 1blankz7** [comment]
Okay, it's done.

**Comment by Neverlord** [comment]
Thanks for contributing to CAF, you rock!

**Pull request merged**
